<?php echo '<?php'; ?>

/**
 *	This file was automaticly generated by Eve Framework.
 *	Do not modify manually!
 */

define('CADO_DEV', <?php echo $this->dev ? 'true' : 'false' ?>);

class Eve {
	static $dbConfig = <?php var_export($this->dbConfig); ?>;
	static $fileCache = <?php var_export($this->fileCache); ?>; 
	static $pushid =  <?php var_export($this->pushid); ?>;
	static $domains = <?php var_export($this->siteConfig['domains']); ?>;
	static $host = '<?php echo $this->host ?>';
	static $webroot = '<?php echo $this->siteConfig['webroot'] ?>/';
	static $uploads = '<?php echo $this->siteConfig['webroot'] ?>/uploads/';
}

require_once('<?php echo $this->srcRoot ?>/cadolibs/Cado.php');
Cado::init();
Cado::addRoot('framework');

echo BaseSite::factory('<?php echo $this->siteCode ?>')->route(new Request());
