
#Bit automaticly generated by EVE Framework
<VirtualHost *:80>
  <?php $first = true; ?>
  <?php foreach ($this->siteConfig['domains'] as $domain): ?>
  <?php echo $first ? 'ServerName' : 'ServerAlias'; $first = false; ?> <?php echo $domain; ?>

  ServerAlias *.<?php echo $domain; ?>
  
  <?php endforeach; ?>
  DocumentRoot <?php echo $this->siteConfig['webDir']; ?>
  
  <Directory />
	AllowOverride All
	Options FollowSymLinks
	Order allow,deny
	allow from all
  </Directory>
</VirtualHost>
