<?php echo '<?php'; ?>

/**
 *	This file was automaticly generated by Eve Framework.
 *	Do not modify manually!
 */

chdir(dirname(__FILE__));
require_once('<?php echo $this->srcRoot ?>/evelibs/Eve.php');
Eve::init(
	<?php echo var_export($this->siteConfig['libs'], true) ?>, 
	<?php echo var_export($this->siteConfig['cacheDir'], true) ?>, 
	<?php echo var_export($this->dev, true) ?>
	);

Site::run();
